CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, username TEXT NOT NULL, username_lc TEXT NOT NULL UNIQUE, salt TEXT NOT NULL, hash TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY, body TEXT, link TEXT, media_key TEXT, media_type TEXT, poll TEXT, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS likes(post_id INTEGER, user_id INTEGER, PRIMARY KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS votes(post_id INTEGER, user_id INTEGER, opt INTEGER, PRIMARY KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, from_owner INTEGER NOT NULL, body TEXT NOT NULL, created INTEGER NOT NULL);
